### ISSUE TITLE
Add support for self-hosted Gitlab

### ISSUE THREAD

**Issue by EslaMx7** [ahmadalfy/gitlab-explorer#16]
We are using a self-hosted version of Gitlab in my company, and I think it will be a good option to support that.

My initial assumption is just adding a `baseUrl` in the `env` file, and default it to the official Gitlab API, and use this value when constructing the full API URL.

I will give it a try and send you a proper PR.

**Comment by ahmadalfy** [comment]
Thank you, that can be done indeed. I think @mohamedluay planned to do that 🤣

**Comment by EslaMx7** [comment]
@mohamedluay Done 😋
@ahmadalfy Please review 😎
