### ISSUE TITLE
Enable pagination params

### ISSUE THREAD

**Issue by ahmed-serag** [ahmadalfy/gitlab-explorer#28]
Currently when requesting (projects, groups, members, commit diffs) beyond the API limit you only get 100 entry. The system should detect that and retrieve the next pages till all data is fetched

**Comment by ahmadalfy** [comment]
Should be handled [here](https://github.com/ahmadalfy/gitlab-explorer/pull/26/commits/3fe7a7bb888c910d889337483fb6ff4c1e47134e)

Some requests need date params to avoid requesting all the data again

**Comment by ahmadalfy** [comment]
Done in #26
